<?php
use PHPUnit\Framework\TestCase;
final class OrionImprovementTicketPolicyTest extends TestCase{
 public function test_exposes_closed_gap_types():void{$this->assertSame(array('knowledge','catalogue','product_data','routing','provider','technical'),Orion_Improvement_Ticket_Policy::types());}
 public function test_classifies_known_failure_reasons():void{$this->assertSame('knowledge',Orion_Improvement_Ticket_Policy::classify_reason('knowledge_no_results'));$this->assertSame('catalogue',Orion_Improvement_Ticket_Policy::classify_reason('catalogue_no_candidates'));$this->assertSame('product_data',Orion_Improvement_Ticket_Policy::classify_reason('required_product_missing'));$this->assertSame('provider',Orion_Improvement_Ticket_Policy::classify_reason('answer_provider_error'));$this->assertSame('routing',Orion_Improvement_Ticket_Policy::classify_reason('classifier_requested_review'));}
 public function test_only_knowledge_gaps_can_publish_to_knowledge():void{$this->assertTrue(Orion_Improvement_Ticket_Policy::can_publish_to_knowledge('knowledge'));foreach(array('catalogue','product_data','routing','provider','technical')as$type)$this->assertFalse(Orion_Improvement_Ticket_Policy::can_publish_to_knowledge($type));}
 public function test_ticket_workflow_prevents_unverified_shortcuts():void{$this->assertTrue(Orion_Improvement_Ticket_Policy::can_ticket_transition('backlog','planned'));$this->assertTrue(Orion_Improvement_Ticket_Policy::can_ticket_transition('planned','in_progress'));$this->assertTrue(Orion_Improvement_Ticket_Policy::can_ticket_transition('in_progress','validating'));$this->assertTrue(Orion_Improvement_Ticket_Policy::can_ticket_transition('validating','resolved'));$this->assertFalse(Orion_Improvement_Ticket_Policy::can_ticket_transition('backlog','resolved'));$this->assertFalse(Orion_Improvement_Ticket_Policy::can_ticket_transition('resolved','backlog'));}
 public function test_resolved_and_dismissed_tickets_can_be_reopened_safely():void{$this->assertTrue(Orion_Improvement_Ticket_Policy::can_ticket_transition('resolved','validating'));$this->assertTrue(Orion_Improvement_Ticket_Policy::can_ticket_transition('dismissed','backlog'));}
 public function test_priority_suggestion_uses_repetition_without_overriding_manager():void{$this->assertSame('low',Orion_Improvement_Ticket_Policy::suggested_priority(1,1));$this->assertSame('normal',Orion_Improvement_Ticket_Policy::suggested_priority(2,2));$this->assertSame('high',Orion_Improvement_Ticket_Policy::suggested_priority(5,3));$this->assertSame('critical',Orion_Improvement_Ticket_Policy::suggested_priority(10,8));}
 public function test_every_type_has_actionable_guidance():void{foreach(Orion_Improvement_Ticket_Policy::types()as$type){$this->assertNotSame('',Orion_Improvement_Ticket_Policy::label($type));$this->assertGreaterThan(30,strlen(Orion_Improvement_Ticket_Policy::recommended_action($type)));}}
}
