<?php
use PHPUnit\Framework\TestCase;
final class OrionImprovementTicketPolicyTest extends TestCase{
 public function test_exposes_closed_gap_types():void{$this->assertSame(array('knowledge','catalogue','product_data','routing','provider','technical'),Orion_Improvement_Ticket_Policy::types());}
 public function test_classifies_known_failure_reasons():void{$this->assertSame('knowledge',Orion_Improvement_Ticket_Policy::classify_reason('knowledge_no_results'));$this->assertSame('knowledge',Orion_Improvement_Ticket_Policy::classify_reason('knowledge_not_supported'));$this->assertSame('catalogue',Orion_Improvement_Ticket_Policy::classify_reason('catalogue_no_candidates'));$this->assertSame('product_data',Orion_Improvement_Ticket_Policy::classify_reason('required_product_missing'));$this->assertSame('provider',Orion_Improvement_Ticket_Policy::classify_reason('answer_provider_error'));$this->assertSame('routing',Orion_Improvement_Ticket_Policy::classify_reason('classifier_requested_review'));}
 public function test_classifies_legacy_reasons_conservatively():void{$this->assertSame('routing',Orion_Improvement_Ticket_Policy::classify_reason('manager_follow_up'));$this->assertSame('routing',Orion_Improvement_Ticket_Policy::classify_reason('classifier_requested_handoff'));$this->assertSame('technical',Orion_Improvement_Ticket_Policy::classify_reason('unexpected_failure'));}
 public function test_uses_safe_keyword_fallbacks():void{$this->assertSame('provider',Orion_Improvement_Ticket_Policy::classify_reason('selection_timeout'));$this->assertSame('knowledge',Orion_Improvement_Ticket_Policy::classify_reason('policy_missing'));$this->assertSame('catalogue',Orion_Improvement_Ticket_Policy::classify_reason('stock_not_found'));$this->assertSame('product_data',Orion_Improvement_Ticket_Policy::classify_reason('compatibility_evidence_missing'));$this->assertSame('routing',Orion_Improvement_Ticket_Policy::classify_reason('intent_mismatch'));}
 public function test_only_knowledge_gaps_can_publish_to_knowledge():void{$this->assertTrue(Orion_Improvement_Ticket_Policy::can_publish_to_knowledge('knowledge'));foreach(array('catalogue','product_data','routing','provider','technical')as$type)$this->assertFalse(Orion_Improvement_Ticket_Policy::can_publish_to_knowledge($type));}
 public function test_every_type_has_actionable_guidance():void{foreach(Orion_Improvement_Ticket_Policy::types()as$type){$this->assertNotSame('',$this->label($type));$this->assertGreaterThan(30,strlen(Orion_Improvement_Ticket_Policy::recommended_action($type)));}}
 private function label(string $type):string{return Orion_Improvement_Ticket_Policy::label($type);}
}
