<?php
use PHPUnit\Framework\TestCase;
final class OrionPolicyEvidenceTest extends TestCase{
 private array $docs=array(array('title'=>'Weekend delivery','content'=>'Saturday delivery can be arranged by request. The exact weekend surcharge is £7.99.'));
 public function test_accepts_complete_answer_with_verbatim_evidence():void{$assessment=Orion_Policy_Evidence::assess(array('supported'=>true,'answer'=>'Saturday delivery is available for an extra £7.99.','requirements'=>array(array('requirement'=>'Saturday availability','supported'=>true,'evidence'=>'Saturday delivery can be arranged by request.'),array('requirement'=>'Exact surcharge','supported'=>true,'evidence'=>'The exact weekend surcharge is £7.99.'))),$this->docs);$this->assertTrue($assessment['supported']);$this->assertCount(2,$assessment['requirements']);}
 public function test_rejects_partial_answer_when_one_requirement_is_unknown():void{$assessment=Orion_Policy_Evidence::assess(array('supported'=>false,'answer'=>'','requirements'=>array(array('requirement'=>'Saturday availability','supported'=>true,'evidence'=>'Saturday delivery can be arranged by request.'),array('requirement'=>'Exact surcharge','supported'=>false,'evidence'=>''))),array(array('content'=>'Saturday delivery can be arranged by request, subject to an additional charge.')));$this->assertFalse($assessment['supported']);$this->assertSame(array('Exact surcharge'),$assessment['unsupported_requirements']);}
 public function test_rejects_top_level_supported_without_requirements():void{$assessment=Orion_Policy_Evidence::assess(array('supported'=>true,'answer'=>'Yes.'),$this->docs);$this->assertFalse($assessment['supported']);}
 public function test_rejects_fabricated_evidence():void{$assessment=Orion_Policy_Evidence::assess(array('supported'=>true,'answer'=>'The surcharge is £12.','requirements'=>array(array('requirement'=>'Exact surcharge','supported'=>true,'evidence'=>'The exact weekend surcharge is £12.'))),$this->docs);$this->assertFalse($assessment['supported']);}
 public function test_rejects_empty_answer_even_when_evidence_is_complete():void{$assessment=Orion_Policy_Evidence::assess(array('supported'=>true,'answer'=>'','requirements'=>array(array('requirement'=>'Saturday availability','supported'=>true,'evidence'=>'Saturday delivery can be arranged by request.'))),$this->docs);$this->assertFalse($assessment['supported']);}
}
