<?php
if (!defined('ABSPATH')) { exit; }

final class Orion_Manager_Handoff {
    private string $table;
    private string $events_table;

    public function __construct(){global$wpdb;$this->table=$wpdb->prefix.'orion_ai_handoffs';$this->events_table=$wpdb->prefix.'orion_ai_handoff_events';}
    public function create(int $conversation_id,string $question,array $context):int{global$wpdb;$reason=sanitize_key((string)($context['failure_stage']??'unanswered'));$trace_id=absint($context['trace_id']??0);$now=current_time('mysql',true);$inserted=$wpdb->insert($this->table,array('conversation_id'=>$conversation_id,'trace_id'=>$trace_id?:null,'question'=>sanitize_textarea_field($question),'context_json'=>wp_json_encode($context),'reason_code'=>$reason?:'unanswered','knowledge_title'=>'','resolution_note'=>'','knowledge_source_url'=>'','knowledge_document_id'=>null,'knowledge_published_at'=>null,'status'=>Orion_Manager_Queue_Policy::STATUS_NEW,'resolved_at'=>null,'created_at'=>$now,'updated_at'=>$now));if(false===$inserted)return 0;$id=(int)$wpdb->insert_id;$this->record_event($id,0,'created','',Orion_Manager_Queue_Policy::STATUS_NEW,array('reason_code'=>$reason?:'unanswered','trace_id'=>$trace_id));return$id;}
    public function get(int $id):?array{global$wpdb;if($id<1)return null;$item=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$this->table} WHERE id=%d",$id),ARRAY_A);return is_array($item)?$item:null;}
    public function all(int $limit=100,array $filters=array()):array{global$wpdb;$limit=max(1,min(500,$limit));$where=array('1=1');$params=array();$status=sanitize_key((string)($filters['status']??''));if(Orion_Manager_Queue_Policy::is_status($status)){$where[]='status=%s';$params[]=$status;}$reason=sanitize_key((string)($filters['reason_code']??''));if($reason!==''){$where[]='reason_code=%s';$params[]=$reason;}$sql="SELECT * FROM {$this->table} WHERE ".implode(' AND ',$where)." ORDER BY CASE status WHEN 'new' THEN 0 WHEN 'in_progress' THEN 1 WHEN 'resolved' THEN 2 ELSE 3 END,id DESC LIMIT %d";$params[]=$limit;return$wpdb->get_results($wpdb->prepare($sql,$params),ARRAY_A)?:array();}
    public function counts():array{global$wpdb;$counts=array_fill_keys(Orion_Manager_Queue_Policy::statuses(),0);$rows=$wpdb->get_results("SELECT status,COUNT(*) total FROM {$this->table} GROUP BY status",ARRAY_A)?:array();foreach($rows as$row){$status=(string)($row['status']??'');if(array_key_exists($status,$counts))$counts[$status]=(int)($row['total']??0);}return$counts;}
    public function reason_counts():array{global$wpdb;return$wpdb->get_results("SELECT reason_code,COUNT(*) total FROM {$this->table} GROUP BY reason_code ORDER BY total DESC,reason_code ASC",ARRAY_A)?:array();}
    public function save_review(int $id,string $title,string $guidance,string $source_url,int $user_id):bool{global$wpdb;$item=$this->get($id);if(!$item||Orion_Manager_Queue_Policy::is_terminal((string)$item['status']))return false;$title=mb_substr(sanitize_text_field($title),0,240);$guidance=mb_substr(trim(wp_kses_post($guidance)),0,12000);$source_url=$this->source_url($source_url);$from=(string)$item['status'];$to=$from===Orion_Manager_Queue_Policy::STATUS_NEW?Orion_Manager_Queue_Policy::STATUS_IN_PROGRESS:$from;$updated=$wpdb->update($this->table,array('knowledge_title'=>$title,'resolution_note'=>$guidance,'knowledge_source_url'=>$source_url,'status'=>$to,'updated_at'=>current_time('mysql',true)),array('id'=>$id));if(false===$updated)return false;$this->record_event($id,$user_id,'review_saved',$from,$to,array('has_guidance'=>$guidance!=='','has_source'=>$source_url!==''));return true;}
    public function mark_knowledge_added(int $id,int $document_id,int $user_id):bool{global$wpdb;$item=$this->get($id);if(!$item||$document_id<1||Orion_Manager_Queue_Policy::is_terminal((string)$item['status']))return false;$from=(string)$item['status'];$now=current_time('mysql',true);$updated=$wpdb->update($this->table,array('knowledge_document_id'=>$document_id,'knowledge_published_at'=>$now,'status'=>Orion_Manager_Queue_Policy::STATUS_RESOLVED,'resolved_at'=>$now,'updated_at'=>$now),array('id'=>$id));if(false===$updated)return false;$this->record_event($id,$user_id,'knowledge_added',$from,Orion_Manager_Queue_Policy::STATUS_RESOLVED,array('document_id'=>$document_id));return true;}
    public function transition(int $id,string $status,int $user_id=0):bool{global$wpdb;$item=$this->get($id);if(!$item)return false;$from=(string)$item['status'];$status=sanitize_key($status);if(!Orion_Manager_Queue_Policy::can_transition($from,$status))return false;$now=current_time('mysql',true);$updated=$wpdb->update($this->table,array('status'=>$status,'resolved_at'=>Orion_Manager_Queue_Policy::is_terminal($status)?$now:null,'updated_at'=>$now),array('id'=>$id));if(false===$updated)return false;$this->record_event($id,$user_id,'status_changed',$from,$status,array());return true;}
    public function history(int $id,int $limit=30):array{global$wpdb;if($id<1)return array();$limit=max(1,min(100,$limit));return$wpdb->get_results($wpdb->prepare("SELECT * FROM {$this->events_table} WHERE handoff_id=%d ORDER BY id DESC LIMIT %d",$id,$limit),ARRAY_A)?:array();}
    public function delete_terminal_before(string $cutoff,int $limit=1000):int{global$wpdb;$limit=max(1,min(5000,$limit));$ids=$wpdb->get_col($wpdb->prepare("SELECT id FROM {$this->table} WHERE status IN ('resolved','dismissed') AND updated_at<%s ORDER BY id ASC LIMIT %d",$cutoff,$limit))?:array();$ids=array_values(array_filter(array_unique(array_map('absint',$ids))));if(!$ids)return 0;$list=implode(',',$ids);$wpdb->query("DELETE FROM {$this->events_table} WHERE handoff_id IN ({$list})");$wpdb->query("DELETE FROM {$this->table} WHERE id IN ({$list})");return count($ids);}
    private function source_url(string $value):string{$value=esc_url_raw(trim($value));if($value==='')return'';$scheme=strtolower((string)wp_parse_url($value,PHP_URL_SCHEME));return in_array($scheme,array('http','https'),true)?$value:'';}
    private function record_event(int $id,int $user_id,string $event,string $from,string $to,array $payload):void{global$wpdb;$wpdb->insert($this->events_table,array('handoff_id'=>$id,'user_id'=>$user_id?:null,'event_type'=>sanitize_key($event),'from_status'=>sanitize_key($from),'to_status'=>sanitize_key($to),'payload_json'=>$payload?wp_json_encode($payload):null,'created_at'=>current_time('mysql',true)));}
}
