<?php
if(!defined('ABSPATH')){exit;}if(!defined('WP_CLI')||!WP_CLI){return;}
final class Orion_Manager_Queue_CLI_Command{
 public function stats(array $args,array $assoc_args):void{$gaps=new Orion_Manager_Handoff();$rows=array();foreach($gaps->counts()as$status=>$total)$rows[]=array('group'=>'gap_status','value'=>$status,'count'=>$total);foreach($gaps->type_counts()as$type=>$total)$rows[]=array('group'=>'type','value'=>$type,'count'=>$total);foreach($gaps->reason_counts()as$row)$rows[]=array('group'=>'reason','value'=>(string)$row['reason_code'],'count'=>(int)$row['total']);foreach($gaps->ticket_counts()as$status=>$total)$rows[]=array('group'=>'ticket_status','value'=>$status,'count'=>$total);$rows[]=array('group'=>'groups','value'=>'repeated','count'=>count($gaps->groups(500,2)));WP_CLI\Utils\format_items($this->format($assoc_args),$rows,array('group','value','count'));}
 /**
  * List AI improvement gaps. Private customer text requires --details.
  *
  * @subcommand list
  */
 public function list_items(array $args,array $assoc_args):void{$filters=array();$status=sanitize_key((string)($assoc_args['status']??''));$reason=sanitize_key((string)($assoc_args['reason']??''));$type=sanitize_key((string)($assoc_args['type']??''));$group=absint($assoc_args['group']??0);if($status!==''&&!Orion_Manager_Queue_Policy::is_status($status))WP_CLI::error('Unknown status.');if($type!==''&&!in_array($type,Orion_Improvement_Ticket_Policy::types(),true))WP_CLI::error('Unknown improvement type.');if($status!=='')$filters['status']=$status;if($reason!=='')$filters['reason_code']=$reason;if($type!=='')$filters['gap_type']=$type;if($group)$filters['gap_group_id']=$group;$items=(new Orion_Manager_Handoff())->all(max(1,min(200,absint($assoc_args['limit']??50))),$filters);$rows=array();foreach($items as$item){$row=array('id'=>(int)$item['id'],'group_id'=>(int)($item['gap_group_id']??0),'occurrences'=>(int)($item['group_occurrence_count']??1),'conversation_id'=>(int)$item['conversation_id'],'trace_id'=>(int)($item['trace_id']??0),'status'=>(string)$item['status'],'gap_type'=>(string)($item['gap_type']??'technical'),'reason_code'=>(string)$item['reason_code'],'created_at'=>(string)$item['created_at']);if(!empty($assoc_args['details']))$row['question']=(string)$item['question'];$rows[]=$row;}$fields=array('id','group_id','occurrences','conversation_id','trace_id','status','gap_type','reason_code','created_at');if(!empty($assoc_args['details']))$fields[]='question';WP_CLI\Utils\format_items($this->format($assoc_args),$rows,$fields);}
 /**
  * List repeated improvement groups and ticket status.
  *
  * @subcommand groups
  */
 public function groups(array $args,array $assoc_args):void{$minimum=max(1,absint($assoc_args['minimum']??2));$items=(new Orion_Manager_Handoff())->groups(max(1,min(200,absint($assoc_args['limit']??50))),$minimum);$rows=array();foreach($items as$item)$rows[]=array('group_id'=>(int)$item['id'],'gap_type'=>(string)$item['gap_type'],'reason_code'=>(string)$item['reason_code'],'occurrences'=>(int)$item['occurrence_count'],'open'=>(int)$item['open_count'],'ticket_status'=>!empty($item['ticket_created_at'])?(string)$item['ticket_status']:'','priority'=>!empty($item['ticket_created_at'])?(string)$item['ticket_priority']:'','owner_id'=>(int)($item['ticket_owner_id']??0),'last_seen'=>(string)$item['last_seen_at']);WP_CLI\Utils\format_items($this->format($assoc_args),$rows,array('group_id','gap_type','reason_code','occurrences','open','ticket_status','priority','owner_id','last_seen'));}
 /**
  * Show one internal improvement ticket. Private plans require --details.
  *
  * @subcommand ticket
  */
 public function ticket(array $args,array $assoc_args):void{$id=absint($args[0]??0);if(!$id)WP_CLI::error('Provide a group ID.');$gaps=new Orion_Manager_Handoff();$group=$gaps->get_group($id);if(!$group)WP_CLI::error('Improvement group #'.$id.' does not exist.');$summary=array('group_id'=>$id,'gap_type'=>(string)$group['gap_type'],'reason_code'=>(string)$group['reason_code'],'occurrences'=>(int)$group['occurrence_count'],'open'=>(int)$group['open_count'],'ticket_created'=>!empty($group['ticket_created_at']),'ticket_status'=>(string)($group['ticket_status']??''),'priority'=>(string)($group['ticket_priority']??''),'owner_id'=>(int)($group['ticket_owner_id']??0),'ticket_created_at'=>$group['ticket_created_at']??null,'ticket_updated_at'=>$group['ticket_updated_at']??null,'ticket_resolved_at'=>$group['ticket_resolved_at']??null,'history'=>$gaps->ticket_history($id,50));if(!empty($assoc_args['details'])){$summary['title']=(string)($group['ticket_title']??'');$summary['fix_plan']=(string)($group['ticket_plan']??'');$summary['verification']=(string)($group['ticket_verification']??'');$summary['reference_url']=(string)($group['ticket_reference_url']??'');$summary['representative_question']=(string)$group['representative_question'];}WP_CLI::log(wp_json_encode($summary,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES));}
 public function show(array $args,array $assoc_args):void{$id=absint($args[0]??0);if(!$id)WP_CLI::error('Provide an improvement gap ID.');$gaps=new Orion_Manager_Handoff();$item=$gaps->get($id);if(!$item)WP_CLI::error('Improvement gap #'.$id.' does not exist.');$type=Orion_Improvement_Ticket_Policy::normalize((string)($item['gap_type']??''));$summary=array('id'=>(int)$item['id'],'group_id'=>(int)($item['gap_group_id']??0),'group_occurrences'=>(int)($item['group_occurrence_count']??1),'conversation_id'=>(int)$item['conversation_id'],'trace_id'=>(int)($item['trace_id']??0),'status'=>(string)$item['status'],'gap_type'=>$type,'reason_code'=>(string)$item['reason_code'],'recommended_action'=>Orion_Improvement_Ticket_Policy::recommended_action($type),'knowledge_document_id'=>(int)($item['knowledge_document_id']??0),'created_at'=>(string)$item['created_at'],'updated_at'=>(string)$item['updated_at'],'history'=>$gaps->history($id,50));if(!empty($assoc_args['details'])){$summary['question']=(string)$item['question'];$summary['review_title']=(string)($item['knowledge_title']??'');$summary['review_notes']=(string)($item['resolution_note']??'');$summary['source_url']=(string)($item['knowledge_source_url']??'');$context=json_decode((string)($item['context_json']??''),true);$summary['diagnostic_context']=is_array($context)?$context:array();}WP_CLI::log(wp_json_encode($summary,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES));}
 public function schema(array $args,array $assoc_args):void{global$wpdb;$table=$wpdb->prefix.'orion_ai_handoffs';$groups_table=$wpdb->prefix.'orion_ai_gap_groups';$events_table=$wpdb->prefix.'orion_ai_gap_group_events';$columns=$wpdb->get_col("SHOW COLUMNS FROM {$table}",0)?:array();$group_columns=$wpdb->get_col("SHOW COLUMNS FROM {$groups_table}",0)?:array();$rows=array();$missing=0;foreach(array('gap_type','gap_group_id','knowledge_title','knowledge_source_url','knowledge_document_id','knowledge_published_at')as$column){$present=in_array($column,$columns,true);if(!$present)$missing++;$rows[]=array('object'=>$column,'status'=>$present?'OK':'MISSING');}foreach(array('ticket_status','ticket_priority','ticket_title','ticket_owner_id','ticket_plan','ticket_verification','ticket_reference_url','ticket_created_at','ticket_resolved_at','ticket_updated_at')as$column){$present=in_array($column,$group_columns,true);if(!$present)$missing++;$rows[]=array('object'=>'group.'.$column,'status'=>$present?'OK':'MISSING');}foreach(array($groups_table=>$wpdb->esc_like($groups_table),$events_table=>$wpdb->esc_like($events_table))as$name=>$pattern){$present=(string)$wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s',$pattern))===$name;if(!$present)$missing++;$rows[]=array('object'=>'table:'.str_replace($wpdb->prefix,'',$name),'status'=>$present?'OK':'MISSING');}WP_CLI\Utils\format_items('table',$rows,array('object','status'));if($missing)WP_CLI::warning($missing.' required schema object(s) missing. Run `wp orion-ai migrate --apply`.');else WP_CLI::success('AI improvement schema is ready.');}
 private function format(array $args):string{$format=sanitize_key((string)($args['format']??'table'));return in_array($format,array('table','json','csv','yaml'),true)?$format:'table';}
}
WP_CLI::add_command('orion-ai gaps','Orion_Manager_Queue_CLI_Command');
