<?php
if(!defined('ABSPATH')){exit;}if(!defined('WP_CLI')||!WP_CLI){return;}
final class Orion_Manager_Queue_CLI_Command{
 public function stats(array $args,array $assoc_args):void{$gaps=new Orion_Manager_Handoff();$rows=array();foreach($gaps->counts()as$status=>$total)$rows[]=array('group'=>'status','value'=>$status,'count'=>$total);foreach($gaps->type_counts()as$type=>$total)$rows[]=array('group'=>'type','value'=>$type,'count'=>$total);foreach($gaps->reason_counts()as$row)$rows[]=array('group'=>'reason','value'=>(string)$row['reason_code'],'count'=>(int)$row['total']);$rows[]=array('group'=>'groups','value'=>'repeated','count'=>count($gaps->groups(500,2)));WP_CLI\Utils\format_items($this->format($assoc_args),$rows,array('group','value','count'));}
 /** @subcommand list */
 public function list_items(array $args,array $assoc_args):void{$filters=array();$status=sanitize_key((string)($assoc_args['status']??''));$reason=sanitize_key((string)($assoc_args['reason']??''));$type=sanitize_key((string)($assoc_args['type']??''));$group=absint($assoc_args['group']??0);if($status!==''&&!Orion_Manager_Queue_Policy::is_status($status))WP_CLI::error('Unknown status.');if($type!==''&&!in_array($type,Orion_Improvement_Ticket_Policy::types(),true))WP_CLI::error('Unknown improvement type.');if($status!=='')$filters['status']=$status;if($reason!=='')$filters['reason_code']=$reason;if($type!=='')$filters['gap_type']=$type;if($group)$filters['gap_group_id']=$group;$items=(new Orion_Manager_Handoff())->all(max(1,min(200,absint($assoc_args['limit']??50))),$filters);$rows=array();foreach($items as$item){$row=array('id'=>(int)$item['id'],'group_id'=>(int)($item['gap_group_id']??0),'occurrences'=>(int)($item['group_occurrence_count']??1),'conversation_id'=>(int)$item['conversation_id'],'trace_id'=>(int)($item['trace_id']??0),'status'=>(string)$item['status'],'gap_type'=>(string)($item['gap_type']??'technical'),'reason_code'=>(string)$item['reason_code'],'created_at'=>(string)$item['created_at']);if(!empty($assoc_args['details']))$row['question']=(string)$item['question'];$rows[]=$row;}$fields=array('id','group_id','occurrences','conversation_id','trace_id','status','gap_type','reason_code','created_at');if(!empty($assoc_args['details']))$fields[]='question';WP_CLI\Utils\format_items($this->format($assoc_args),$rows,$fields);}
 /** List repeated improvement groups without full customer dialogue. @subcommand groups */
 public function groups(array $args,array $assoc_args):void{$minimum=max(2,absint($assoc_args['minimum']??2));$items=(new Orion_Manager_Handoff())->groups(max(1,min(200,absint($assoc_args['limit']??50))),$minimum);$rows=array();foreach($items as$item)$rows[]=array('group_id'=>(int)$item['id'],'gap_type'=>(string)$item['gap_type'],'reason_code'=>(string)$item['reason_code'],'intent'=>(string)$item['intent'],'topic'=>(string)$item['topic'],'occurrences'=>(int)$item['occurrence_count'],'open'=>(int)$item['open_count'],'last_seen'=>(string)$item['last_seen_at']);WP_CLI\Utils\format_items($this->format($assoc_args),$rows,array('group_id','gap_type','reason_code','intent','topic','occurrences','open','last_seen'));}
 public function show(array $args,array $assoc_args):void{$id=absint($args[0]??0);if(!$id)WP_CLI::error('Provide an improvement gap ID.');$gaps=new Orion_Manager_Handoff();$item=$gaps->get($id);if(!$item)WP_CLI::error('Improvement gap #'.$id.' does not exist.');$type=Orion_Improvement_Ticket_Policy::normalize((string)($item['gap_type']??''));$summary=array('id'=>(int)$item['id'],'group_id'=>(int)($item['gap_group_id']??0),'group_occurrences'=>(int)($item['group_occurrence_count']??1),'group_intent'=>(string)($item['group_intent']??''),'group_topic'=>(string)($item['group_topic']??''),'conversation_id'=>(int)$item['conversation_id'],'trace_id'=>(int)($item['trace_id']??0),'status'=>(string)$item['status'],'gap_type'=>$type,'gap_type_label'=>Orion_Improvement_Ticket_Policy::label($type),'reason_code'=>(string)$item['reason_code'],'recommended_action'=>Orion_Improvement_Ticket_Policy::recommended_action($type),'can_publish_to_knowledge'=>Orion_Improvement_Ticket_Policy::can_publish_to_knowledge($type),'knowledge_document_id'=>(int)($item['knowledge_document_id']??0),'created_at'=>(string)$item['created_at'],'updated_at'=>(string)$item['updated_at'],'history'=>$gaps->history($id,50));if(!empty($assoc_args['details'])){$summary['question']=(string)$item['question'];$summary['review_title']=(string)($item['knowledge_title']??'');$summary['review_notes']=(string)($item['resolution_note']??'');$summary['source_url']=(string)($item['knowledge_source_url']??'');$context=json_decode((string)($item['context_json']??''),true);$summary['diagnostic_context']=is_array($context)?$context:array();}WP_CLI::log(wp_json_encode($summary,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES));}
 public function schema(array $args,array $assoc_args):void{global$wpdb;$table=$wpdb->prefix.'orion_ai_handoffs';$groups_table=$wpdb->prefix.'orion_ai_gap_groups';$columns=$wpdb->get_col("SHOW COLUMNS FROM {$table}",0)?:array();$required=array('gap_type','gap_group_id','knowledge_title','knowledge_source_url','knowledge_document_id','knowledge_published_at');$rows=array();$missing=0;foreach($required as$column){$present=in_array($column,$columns,true);if(!$present)$missing++;$rows[]=array('object'=>$column,'status'=>$present?'OK':'MISSING');}$groups_ready===(string)$wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s',$wpdb->esc_like($groups_table)));$rows[]=array('object'=>'table:orion_ai_gap_groups','status'=>$groups_ready?'OK':'MISSING');if(!$groups_ready)$missing++;WP_CLI\Utils\format_items('table',$rows,array('object','status'));if($missing)WP_CLI::warning($missing.' required schema object(s) missing. Run `wp orion-ai migrate --apply`.');else WP_CLI::success('AI improvement schema is ready.');}
 private function format(array $args):string{$format=sanitize_key((string)($args['format']??'table'));return in_array($format,array('table','json','csv','yaml'),true)?$format:'table';}
}
WP_CLI::add_command('orion-ai gaps','Orion_Manager_Queue_CLI_Command');
