<?php
if(!defined('ABSPATH')){exit;}
final class Orion_Product_Search{
 public function search(array|string $request,int $legacy_limit=6):array{if(!function_exists('wc_get_products'))return array();$args=is_array($request)?$request:array('query'=>$request,'limit'=>$legacy_limit);$query=sanitize_text_field((string)($args['query']??''));$limit=max(1,min(8,absint($args['limit']??6)));$in_stock=!isset($args['in_stock'])||filter_var($args['in_stock'],FILTER_VALIDATE_BOOLEAN);$tokens=$this->keywords($query);if(!$tokens)return array();$ids=array();$base=array('status'=>'publish','visibility'=>'visible','limit'=>20,'return'=>'ids');if($in_stock)$base['stock_status']=array('instock','onbackorder');$exact=$base;$exact['search']=$query;$ids=array_map('absint',wc_get_products($exact));foreach(array_slice($tokens,0,8)as$token){$q=$base;$q['search']=$token;$ids=array_values(array_unique(array_merge($ids,array_map('absint',wc_get_products($q)))));if(count($ids)>=60)break;}$sku=wc_get_product_id_by_sku($query);if($sku)$ids[]=(int)$sku;$scored=array();foreach(array_unique($ids)as$id){$item=$this->get_product((int)$id);if(!$item||($in_stock&&!$item['in_stock']))continue;$score=$this->score($item,$tokens,$query);if($score<1)continue;$scored[]=array('score'=>$score,'item'=>$item);}usort($scored,static fn($a,$b)=>$b['score']<=>$a['score']);return array_values(array_map(static fn($row)=>$row['item'],array_slice($scored,0,$limit)));}
 public function get_product(int $id):?array{if(!function_exists('wc_get_product')||$id<1)return null;try{$p=wc_get_product($id);return(!$p||!$p->is_visible())?null:$this->format($p);}catch(Throwable $e){error_log('Orion AI product lookup failed for '.absint($id));return null;}}
 private function score(array $item,array $tokens,string $query):int{$name=strtolower($item['name']);$cats=strtolower(implode(' ',$item['categories']));$desc=strtolower($item['short_description']);$attrs=strtolower(wp_json_encode($item['attributes']));$hay=$name.' '.$cats.' '.$desc.' '.$attrs;$matched=0;$score=0;foreach($tokens as$t)if(str_contains($hay,$t)){$matched++;$score+=str_contains($name,$t)?4:(str_contains($cats,$t)?3:1);}if($matched<min(2,count($tokens)))return 0;$special=array('floor','garage','epoxy','tile','masonry','exterior','outdoor','ceiling','primer');$required=array_values(array_intersect($tokens,$special));if($required&&!array_filter($required,static fn($t)=>str_contains($hay,$t)))return 0;if((str_contains(strtolower($query),'floor')||str_contains(strtolower($query),'garage'))&&preg_match('/walls? and ceilings?|walls?|ceilings?/',$desc)&&!preg_match('/floor|garage|epoxy/',$hay))return 0;return$score;}
 private function keywords(string $text):array{$stop=array('what','which','with','that','this','from','have','need','show','find','looking','please','would','could','product','products','for','the','and','are','you','your','some','best','high','area','durable');$tokens=preg_split('/[^a-z0-9-]+/i',strtolower($text))?:array();return array_values(array_unique(array_filter($tokens,static fn($t)=>strlen($t)>2&&!in_array($t,$stop,true))));}
 private function format(WC_Product $p):array{$attrs=array();foreach(array_slice($p->get_attributes(),0,8)as$a){if($a->is_taxonomy()){$values=wc_get_product_terms($p->get_id(),$a->get_name(),array('fields'=>'names'));$label=wc_attribute_label($a->get_name());}else{$values=$a->get_options();$label=$a->get_name();}if(!is_wp_error($values)&&$values)$attrs[$label]=array_values(array_map('strval',$values));}$cats=wp_get_post_terms($p->get_id(),'product_cat',array('fields'=>'names'));if(is_wp_error($cats))$cats=array();$html=$p->get_price_html();$item=array('id'=>$p->get_id(),'sku'=>$p->get_sku(),'name'=>$p->get_name(),'type'=>$p->get_type(),'url'=>$p->get_permalink(),'image'=>wp_get_attachment_image_url($p->get_image_id(),'woocommerce_thumbnail')?:wc_placeholder_img_src('woocommerce_thumbnail'),'price_text'=>html_entity_decode(trim(wp_strip_all_tags($html)),ENT_QUOTES|ENT_HTML5,get_bloginfo('charset')?:'UTF-8'),'price'=>$p->get_price(),'in_stock'=>$p->is_in_stock(),'stock_status'=>$p->get_stock_status(),'short_description'=>mb_substr(wp_strip_all_tags($p->get_short_description()),0,500),'categories'=>array_values($cats),'attributes'=>$attrs,'can_add_to_cart'=>$p->is_type('simple')&&$p->is_purchasable()&&$p->is_in_stock());if($p->is_type('variable')){$item['variation_attributes']=$p->get_variation_attributes();$item['variation_count']=count($p->get_children());}return$item;}
}
