<?php
if(!defined('ABSPATH')){exit;}
final class Orion_Manager_Handoff{
 private string $table;private string $events_table;private string $groups_table;
 public function __construct(){global$wpdb;$this->table=$wpdb->prefix.'orion_ai_handoffs';$this->events_table=$wpdb->prefix.'orion_ai_handoff_events';$this->groups_table=$wpdb->prefix.'orion_ai_gap_groups';}
 public function create(int $conversation_id,string $question,array $context):int{global$wpdb;$reason=sanitize_key((string)($context['failure_stage']??'unanswered'))?:'unanswered';$type=Orion_Improvement_Ticket_Policy::classify_reason($reason);$trace_id=absint($context['trace_id']??0);$now=current_time('mysql',true);$inserted=$wpdb->insert($this->table,array('conversation_id'=>$conversation_id,'trace_id'=>$trace_id?:null,'question'=>sanitize_textarea_field($question),'context_json'=>wp_json_encode($context),'reason_code'=>$reason,'gap_type'=>$type,'gap_group_id'=>null,'knowledge_title'=>'','resolution_note'=>'','knowledge_source_url'=>'','knowledge_document_id'=>null,'knowledge_published_at'=>null,'status'=>Orion_Manager_Queue_Policy::STATUS_NEW,'resolved_at'=>null,'created_at'=>$now,'updated_at'=>$now));if(false===$inserted){error_log('Orion AI gap insert failed: '.$wpdb->last_error);return 0;}$id=(int)$wpdb->insert_id;$group_id=$this->assign_group($id,$question,$type,$reason,$context,$now);$this->record_event($id,0,'created','',Orion_Manager_Queue_Policy::STATUS_NEW,array('reason_code'=>$reason,'gap_type'=>$type,'gap_group_id'=>$group_id,'trace_id'=>$trace_id));return$id;}
 public function get(int $id):?array{global$wpdb;if($id<1)return null;$item=$wpdb->get_row($wpdb->prepare("SELECT h.*,COALESCE(g.occurrence_count,1) group_occurrence_count,g.intent group_intent,g.topic group_topic,g.representative_question group_question FROM {$this->table} h LEFT JOIN {$this->groups_table} g ON g.id=h.gap_group_id WHERE h.id=%d",$id),ARRAY_A);return is_array($item)?$item:null;}
 public function all(int $limit=100,array $filters=array(),int $offset=0):array{global$wpdb;$limit=max(1,min(500,$limit));$offset=max(0,$offset);[$where,$params]=$this->filter_parts($filters);$sql="SELECT h.*,COALESCE(g.occurrence_count,1) group_occurrence_count,g.intent group_intent,g.topic group_topic,g.representative_question group_question FROM {$this->table} h LEFT JOIN {$this->groups_table} g ON g.id=h.gap_group_id WHERE ".implode(' AND ',$where)." ORDER BY CASE h.status WHEN 'new' THEN 0 WHEN 'in_progress' THEN 1 WHEN 'resolved' THEN 2 ELSE 3 END,h.id DESC LIMIT %d OFFSET %d";$params[]=$limit;$params[]=$offset;return$wpdb->get_results($wpdb->prepare($sql,$params),ARRAY_A)?:array();}
 public function total(array $filters=array()):int{global$wpdb;[$where,$params]=$this->filter_parts($filters);$sql="SELECT COUNT(*) FROM {$this->table} h WHERE ".implode(' AND ',$where);return(int)($params?$wpdb->get_var($wpdb->prepare($sql,$params)):$wpdb->get_var($sql));}
 public function groups(int $limit=50,int $minimum=2):array{global$wpdb;$limit=max(1,min(500,$limit));$minimum=max(1,$minimum);$sql="SELECT g.id,g.group_key,g.gap_type,g.reason_code,g.intent,g.topic,g.representative_question,COUNT(h.id) occurrence_count,SUM(CASE WHEN h.status IN ('new','in_progress') THEN 1 ELSE 0 END) open_count,MIN(h.created_at) first_seen_at,MAX(h.created_at) last_seen_at FROM {$this->groups_table} g INNER JOIN {$this->table} h ON h.gap_group_id=g.id GROUP BY g.id,g.group_key,g.gap_type,g.reason_code,g.intent,g.topic,g.representative_question HAVING COUNT(h.id)>=%d ORDER BY occurrence_count DESC,last_seen_at DESC LIMIT %d";return$wpdb->get_results($wpdb->prepare($sql,$minimum,$limit),ARRAY_A)?:array();}
 public function backfill_groups(int $limit=5000):int{global$wpdb;$limit=max(1,min(20000,$limit));$rows=$wpdb->get_results($wpdb->prepare("SELECT id,question,context_json,reason_code,gap_type,created_at FROM {$this->table} WHERE gap_group_id IS NULL OR gap_group_id=0 ORDER BY id ASC LIMIT %d",$limit),ARRAY_A)?:array();$count=0;foreach($rows as$row){$context=json_decode((string)($row['context_json']??''),true);$context=is_array($context)?$context:array();if($this->assign_group((int)$row['id'],(string)$row['question'],Orion_Improvement_Ticket_Policy::normalize((string)$row['gap_type']),(string)$row['reason_code'],$context,(string)$row['created_at']))$count++;}return$count;}
 public function counts():array{global$wpdb;$counts=array_fill_keys(Orion_Manager_Queue_Policy::statuses(),0);$rows=$wpdb->get_results("SELECT status,COUNT(*) total FROM {$this->table} GROUP BY status",ARRAY_A)?:array();foreach($rows as$row){$status=(string)($row['status']??'');if(array_key_exists($status,$counts))$counts[$status]=(int)($row['total']??0);}return$counts;}
 public function reason_counts():array{global$wpdb;return$wpdb->get_results("SELECT reason_code,COUNT(*) total FROM {$this->table} GROUP BY reason_code ORDER BY total DESC,reason_code ASC",ARRAY_A)?:array();}
 public function type_counts():array{global$wpdb;$counts=array_fill_keys(Orion_Improvement_Ticket_Policy::types(),0);$rows=$wpdb->get_results("SELECT gap_type,COUNT(*) total FROM {$this->table} GROUP BY gap_type",ARRAY_A)?:array();foreach($rows as$row){$type=Orion_Improvement_Ticket_Policy::normalize((string)($row['gap_type']??''));$counts[$type]+=(int)($row['total']??0);}return$counts;}
 public function save_review(int $id,string $title,string $guidance,string $source_url,int $user_id):bool{global$wpdb;$item=$this->get($id);if(!$item||Orion_Manager_Queue_Policy::is_terminal((string)$item['status']))return false;$title=mb_substr(sanitize_text_field($title),0,240);$guidance=mb_substr(trim(wp_kses_post($guidance)),0,12000);$source_url=$this->source_url($source_url);$from=(string)$item['status'];$to=$from===Orion_Manager_Queue_Policy::STATUS_NEW?Orion_Manager_Queue_Policy::STATUS_IN_PROGRESS:$from;$updated=$wpdb->update($this->table,array('knowledge_title'=>$title,'resolution_note'=>$guidance,'knowledge_source_url'=>$source_url,'status'=>$to,'updated_at'=>current_time('mysql',true)),array('id'=>$id));if(false===$updated)return false;$this->record_event($id,$user_id,'review_saved',$from,$to,array('gap_type'=>(string)$item['gap_type'],'gap_group_id'=>(int)($item['gap_group_id']??0),'has_guidance'=>$guidance!=='','has_source'=>$source_url!==''));return true;}
 public function mark_knowledge_added(int $id,int $document_id,int $user_id):bool{global$wpdb;$item=$this->get($id);$type=Orion_Improvement_Ticket_Policy::normalize((string)($item['gap_type']??''));if(!$item||$document_id<1||Orion_Manager_Queue_Policy::is_terminal((string)$item['status'])||!Orion_Improvement_Ticket_Policy::can_publish_to_knowledge($type))return false;$from=(string)$item['status'];$now=current_time('mysql',true);$updated=$wpdb->update($this->table,array('knowledge_document_id'=>$document_id,'knowledge_published_at'=>$now,'status'=>Orion_Manager_Queue_Policy::STATUS_RESOLVED,'resolved_at'=>$now,'updated_at'=>$now),array('id'=>$id));if(false===$updated)return false;$this->record_event($id,$user_id,'knowledge_added',$from,Orion_Manager_Queue_Policy::STATUS_RESOLVED,array('gap_type'=>$type,'gap_group_id'=>(int)($item['gap_group_id']??0),'document_id'=>$document_id));return true;}
 public function transition(int $id,string $status,int $user_id=0):bool{global$wpdb;$item=$this->get($id);if(!$item)return false;$from=(string)$item['status'];$status=sanitize_key($status);if(!Orion_Manager_Queue_Policy::can_transition($from,$status))return false;$now=current_time('mysql',true);$updated=$wpdb->update($this->table,array('status'=>$status,'resolved_at'=>Orion_Manager_Queue_Policy::is_terminal($status)?$now:null,'updated_at'=>$now),array('id'=>$id));if(false===$updated)return false;$this->record_event($id,$user_id,'status_changed',$from,$status,array('gap_type'=>(string)$item['gap_type'],'gap_group_id'=>(int)($item['gap_group_id']??0)));return true;}
 public function history(int $id,int $limit=30):array{global$wpdb;if($id<1)return array();$limit=max(1,min(100,$limit));return$wpdb->get_results($wpdb->prepare("SELECT * FROM {$this->events_table} WHERE handoff_id=%d ORDER BY id DESC LIMIT %d",$id,$limit),ARRAY_A)?:array();}
 public function delete_terminal_before(string $cutoff,int $limit=1000):int{global$wpdb;$limit=max(1,min(5000,$limit));$ids=$wpdb->get_col($wpdb->prepare("SELECT id FROM {$this->table} WHERE status IN ('resolved','dismissed') AND updated_at<%s ORDER BY id ASC LIMIT %d",$cutoff,$limit))?:array();$ids=array_values(array_filter(array_unique(array_map('absint',$ids))));if(!$ids)return 0;$list=implode(',',$ids);$group_ids=$wpdb->get_col("SELECT DISTINCT gap_group_id FROM {$this->table} WHERE id IN ({$list}) AND gap_group_id IS NOT NULL")?:array();$wpdb->query("DELETE FROM {$this->events_table} WHERE handoff_id IN ({$list})");$wpdb->query("DELETE FROM {$this->table} WHERE id IN ({$list})");foreach(array_map('absint',$group_ids)as$group_id)$this->refresh_group($group_id);return count($ids);}
 private function assign_group(int $gap_id,string $question,string $type,string $reason,array $context,string $seen_at):int{global$wpdb;if($gap_id<1)return 0;$labels=Orion_Gap_Grouping::labels($context);$key=Orion_Gap_Grouping::key($question,$type,$reason,$context);$group_id=(int)$wpdb->get_var($wpdb->prepare("SELECT id FROM {$this->groups_table} WHERE group_key=%s LIMIT 1",$key));if(!$group_id&&$labels['intent']===''&&$labels['topic']===''){$candidates=$wpdb->get_results($wpdb->prepare("SELECT id,representative_question FROM {$this->groups_table} WHERE gap_type=%s AND reason_code=%s AND intent='' AND topic='' ORDER BY last_seen_at DESC LIMIT 100",$type,$reason),ARRAY_A)?:array();$best=0.0;foreach($candidates as$candidate){$score=Orion_Gap_Grouping::similarity($question,(string)$candidate['representative_question']);if($score>=0.6&&$score>$best){$best=$score;$group_id=(int)$candidate['id'];}}}if(!$group_id){$now=current_time('mysql',true);$inserted=$wpdb->insert($this->groups_table,array('group_key'=>$key,'gap_type'=>$type,'reason_code'=>$reason,'intent'=>$labels['intent'],'topic'=>$labels['topic'],'representative_question'=>sanitize_textarea_field($question),'occurrence_count'=>0,'first_seen_at'=>$seen_at?:$now,'last_seen_at'=>$seen_at?:$now,'created_at'=>$now,'updated_at'=>$now));$group_id=$inserted?(int)$wpdb->insert_id:(int)$wpdb->get_var($wpdb->prepare("SELECT id FROM {$this->groups_table} WHERE group_key=%s LIMIT 1",$key));}if(!$group_id)return 0;$wpdb->update($this->table,array('gap_group_id'=>$group_id),array('id'=>$gap_id));$this->refresh_group($group_id);return$group_id;}
 private function refresh_group(int $group_id):void{global$wpdb;if($group_id<1)return;$stats=$wpdb->get_row($wpdb->prepare("SELECT COUNT(*) total,MIN(created_at) first_seen,MAX(created_at) last_seen FROM {$this->table} WHERE gap_group_id=%d",$group_id),ARRAY_A);$total=(int)($stats['total']??0);if(!$total){$wpdb->delete($this->groups_table,array('id'=>$group_id));return;}$wpdb->update($this->groups_table,array('occurrence_count'=>$total,'first_seen_at'=>(string)$stats['first_seen'],'last_seen_at'=>(string)$stats['last_seen'],'updated_at'=>current_time('mysql',true)),array('id'=>$group_id));}
 private function filter_parts(array $filters):array{$where=array('1=1');$params=array();$status=sanitize_key((string)($filters['status']??''));if(Orion_Manager_Queue_Policy::is_status($status)){$where[]='h.status=%s';$params[]=$status;}$reason=sanitize_key((string)($filters['reason_code']??''));if($reason!==''){$where[]='h.reason_code=%s';$params[]=$reason;}$type=sanitize_key((string)($filters['gap_type']??''));if(in_array($type,Orion_Improvement_Ticket_Policy::types(),true)){$where[]='h.gap_type=%s';$params[]=$type;}$group_id=absint($filters['gap_group_id']??0);if($group_id){$where[]='h.gap_group_id=%d';$params[]=$group_id;}return array($where,$params);}
 private function source_url(string $value):string{$value=esc_url_raw(trim($value));if($value==='')return'';$scheme=strtolower((string)wp_parse_url($value,PHP_URL_SCHEME));return in_array($scheme,array('http','https'),true)?$value:'';}
 private function record_event(int $id,int $user_id,string $event,string $from,string $to,array $payload):void{global$wpdb;$wpdb->insert($this->events_table,array('handoff_id'=>$id,'user_id'=>$user_id?:null,'event_type'=>sanitize_key($event),'from_status'=>sanitize_key($from),'to_status'=>sanitize_key($to),'payload_json'=>$payload?wp_json_encode($payload):null,'created_at'=>current_time('mysql',true)));}
}
