<?php
if(!defined('ABSPATH')){exit;}
final class Orion_AI_Trace_Service{
 private string $table;
 public function __construct(){global$wpdb;$this->table=$wpdb->prefix.'orion_ai_traces';}
 public function begin(int $conversation_id,string $message,array $settings):int{global$wpdb;$provider=Orion_AI_Settings::provider($settings);$model=Orion_AI_Settings::stage_model($settings,'routing',$provider);$wpdb->insert($this->table,array('conversation_id'=>$conversation_id?:null,'trace_key'=>wp_generate_uuid4(),'provider'=>$provider,'model'=>$model,'intent'=>'','topic'=>'','status'=>'running','failure_stage'=>'','failure_reason'=>'','duration_ms'=>0,'payload_json'=>wp_json_encode(array('message'=>sanitize_textarea_field($message),'stages'=>array())),'created_at'=>current_time('mysql',true),'updated_at'=>current_time('mysql',true)));return(int)$wpdb->insert_id;}
 public function update(int $id,array $data):void{global$wpdb;if($id<1)return;$row=$wpdb->get_row($wpdb->prepare("SELECT payload_json FROM {$this->table} WHERE id=%d",$id),ARRAY_A);$payload=json_decode((string)($row['payload_json']??'{}'),true);if(!is_array($payload))$payload=array();$payload=array_replace_recursive($payload,$this->sanitize($data));$updates=array('payload_json'=>wp_json_encode($payload),'updated_at'=>current_time('mysql',true));$limits=array('intent'=>50,'topic'=>100,'status'=>30,'failure_stage'=>80);foreach(array('intent','topic','status','failure_stage','failure_reason','duration_ms')as$key){if(!array_key_exists($key,$data))continue;if('duration_ms'===$key){$updates[$key]=absint($data[$key]);continue;}$value=sanitize_text_field((string)$data[$key]);if(isset($limits[$key]))$value=mb_substr($value,0,$limits[$key]);$updates[$key]=$value;}$wpdb->update($this->table,$updates,array('id'=>$id));}
 public function complete(int $id,string $status,string $stage='',string $reason='',int $duration_ms=0,array $data=array()):void{$data['status']=$status;$data['failure_stage']=$stage;$data['failure_reason']=$reason;$data['duration_ms']=$duration_ms;$this->update($id,$data);}
 public function all(int $limit=100):array{global$wpdb;$limit=max(1,min(500,$limit));return$wpdb->get_results($wpdb->prepare("SELECT id,trace_key,provider,model,intent,topic,status,failure_stage,failure_reason,duration_ms,created_at FROM {$this->table} ORDER BY id DESC LIMIT %d",$limit),ARRAY_A)?:array();}
 public function get(int $id):?array{global$wpdb;$row=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$this->table} WHERE id=%d",$id),ARRAY_A);if(!$row)return null;$row['payload']=json_decode((string)$row['payload_json'],true);unset($row['payload_json']);return$row;}
 private function sanitize(array $data):array{$walk=function($value,$key='')use(&$walk){if(preg_match('/(?:^|[_-])(?:api[_-]?key|secret|authorization|cookie|nonce|password|access[_-]?token|refresh[_-]?token|bearer[_-]?token|auth[_-]?token|id[_-]?token)$|^token$/i',(string)$key))return'[redacted]';if(is_array($value)){foreach($value as$k=>$v)$value[$k]=$walk($v,(string)$k);return$value;}if(is_bool($value)||is_numeric($value)||null===$value)return$value;return mb_substr(sanitize_textarea_field((string)$value),0,4000);};return$walk($data);}
}
