<?php
if(!defined('ABSPATH')){exit;}
final class Orion_Gap_Grouping{
 public static function labels(array $context):array{$classification=is_array($context['classification']??null)?$context['classification']:array();$intent=self::clean((string)($classification['intent']??''));$topic=self::clean((string)($classification['topic']??''));if(in_array($intent,array('unknown','other'),true))$intent='';if(in_array($topic,array('general','unknown','other'),true))$topic='';return array('intent'=>$intent,'topic'=>$topic);}
 public static function key(string $question,string $type,string $reason,array $context=array()):string{$labels=self::labels($context);$basis=$type.'|'.$reason;if($labels['intent']!==''||$labels['topic']!=='')$basis.='|context|'.$labels['intent'].'|'.$labels['topic'];else$basis.='|question|'.self::signature($question);return hash('sha256',$basis);}
 public static function signature(string $question):string{return implode(' ',self::tokens($question));}
 public static function similarity(string $left,string $right):float{$a=self::tokens($left);$b=self::tokens($right);if(!$a||!$b)return 0.0;$intersection=count(array_intersect($a,$b));$union=count(array_unique(array_merge($a,$b)));return$union?$intersection/$union:0.0;}
 private static function tokens(string $text):array{$text=mb_strtolower($text);$text=(string)preg_replace('~https?://\S+|\b\S+@\S+\b~u',' ',$text);$parts=preg_split('/[^\p{L}\p{N}]+/u',$text,-1,PREG_SPLIT_NO_EMPTY)?:array();$stop=array_flip(array('the','and','for','with','that','this','from','into','your','you','are','can','could','would','should','please','need','want','have','has','how','what','when','where','which','there','about','around','exact','estimated','number','yes','not','our','their','will','does','do','is','it','to','of','in','on','a','an','i','we','my'));$tokens=array();foreach($parts as$word){if(isset($stop[$word]))continue;$word=self::stem($word);if(mb_strlen($word)<3&&!ctype_digit($word))continue;$tokens[$word]=true;}$tokens=array_keys($tokens);sort($tokens,SORT_STRING);return$tokens;}
 private static function stem(string $word):string{if($word==='delivery')return'deliver';$length=mb_strlen($word);foreach(array('ing','ed','es','s')as$suffix){$suffix_length=strlen($suffix);if($length>$suffix_length+3&&str_ends_with($word,$suffix))return mb_substr($word,0,$length-$suffix_length);}return$word;}
 private static function clean(string $value):string{$value=mb_strtolower(trim($value));return trim((string)preg_replace('/[^a-z0-9_\-]+/','_',$value),'_');}
}
