<?php
if(!defined('ABSPATH')){exit;}
final class Orion_Product_Index{
 public function register_hooks():void{add_action('woocommerce_new_product',array($this,'index_product'));add_action('woocommerce_update_product',array($this,'index_product'));add_action('before_delete_post',array($this,'delete_post'));}
 public function count():int{global$wpdb;$table=$wpdb->prefix.'orion_ai_product_index';if($wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s',$table))!==$table)return 0;return(int)$wpdb->get_var("SELECT COUNT(*) FROM {$table}");}
 public function reindex_all(int $limit=0):int{if(!function_exists('wc_get_products'))return 0;$ids=array_map('absint',wc_get_products(array('status'=>'publish','return'=>'ids','limit'=>$limit>0?min(5000,$limit):-1,'orderby'=>'ID','order'=>'ASC')));$done=0;foreach($ids as$id)if($this->index_product($id))$done++;if($limit<1)$this->remove_stale($ids);return$done;}
 public function index_product(int $product_id):bool{global$wpdb;if(!function_exists('wc_get_product'))return false;$p=wc_get_product($product_id);if(!$p||'publish'!==get_post_status($product_id)){if($this->table_exists())$wpdb->delete($wpdb->prefix.'orion_ai_product_index',array('product_id'=>$product_id),array('%d'));return false;}$categories=$this->terms($product_id,'product_cat');$tags=$this->terms($product_id,'product_tag');$attributes=array();foreach($p->get_attributes()as$a){$name=$a->get_name();$values=$a->is_taxonomy()?wc_get_product_terms($product_id,$name,array('fields'=>'names')):$a->get_options();if(!is_wp_error($values))$attributes[wc_attribute_label($name)]=array_values(array_map('strval',$values));}$variations=array();if($p->is_type('variable'))foreach(array_slice($p->get_children(),0,200)as$child_id){$v=wc_get_product($child_id);if(!$v)continue;$variations[]=array('id'=>(int)$child_id,'sku'=>$v->get_sku(),'attributes'=>$v->get_variation_attributes(),'description'=>mb_substr(wp_strip_all_tags($v->get_description()),0,300),'stock'=>$v->get_stock_status());}$title=$p->get_name();$content=trim(wp_strip_all_tags($p->get_short_description()).' '.wp_strip_all_tags($p->get_description()));$attribute_text=wp_json_encode(array('attributes'=>$attributes,'variations'=>$variations),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);$hash=hash('sha256',$title.'|'.$content.'|'.implode(' ',$categories).'|'.implode(' ',$tags).'|'.$attribute_text.'|'.$p->get_stock_status().'|'.($p->is_visible()?'1':'0'));if(!$this->table_exists())return false;$now=current_time('mysql',true);return false!==$wpdb->replace($wpdb->prefix.'orion_ai_product_index',array('product_id'=>$product_id,'title'=>$title,'content'=>$content,'categories'=>implode(' | ',$categories),'tags'=>implode(' | ',$tags),'attributes'=>$attribute_text,'product_type'=>$p->get_type(),'stock_status'=>$p->get_stock_status(),'is_visible'=>$p->is_visible()?1:0,'content_hash'=>$hash,'updated_at'=>$now),array('%d','%s','%s','%s','%s','%s','%s','%s','%d','%s','%s'));}
 public function delete_post(int $post_id):void{if('product'!==get_post_type($post_id)||!$this->table_exists())return;global$wpdb;$wpdb->delete($wpdb->prefix.'orion_ai_product_index',array('product_id'=>$post_id),array('%d'));}
 public function search(string $query,int $limit=50):array{global$wpdb;if(!$this->table_exists())return array();$query=trim(sanitize_text_field($query));if($query==='')return array();$table=$wpdb->prefix.'orion_ai_product_index';$limit=max(1,min(100,$limit));$results=array();$sql=$wpdb->prepare("SELECT product_id,MATCH(title,content,categories,tags,attributes) AGAINST (%s IN NATURAL LANGUAGE MODE) AS relevance FROM {$table} WHERE is_visible=1 AND stock_status IN ('instock','onbackorder') AND MATCH(title,content,categories,tags,attributes) AGAINST (%s IN NATURAL LANGUAGE MODE) ORDER BY relevance DESC LIMIT %d",$query,$query,$limit);$rows=$wpdb->get_results($sql,ARRAY_A);if(is_array($rows))foreach($rows as$row)$results[(int)$row['product_id']]=array('score'=>(float)$row['relevance'],'source'=>'catalogue_fulltext');$tokens=$this->tokens($query);if(count($results)<$limit&&$tokens){$where=array();$params=array();foreach(array_slice($tokens,0,8)as$token){$like='%'.$wpdb->esc_like($token).'%';$where[]='(title LIKE %s OR content LIKE %s OR categories LIKE %s OR tags LIKE %s OR attributes LIKE %s)';array_push($params,$like,$like,$like,$like,$like);}$remaining=$limit-count($results);$params[]=$remaining;$fallback="SELECT product_id FROM {$table} WHERE is_visible=1 AND stock_status IN ('instock','onbackorder') AND (".implode(' OR ',$where).") ORDER BY updated_at DESC LIMIT %d";$ids=$wpdb->get_col($wpdb->prepare($fallback,...$params));foreach($ids as$id)if(!isset($results[(int)$id]))$results[(int)$id]=array('score'=>0.01,'source'=>'catalogue_fields');}return$results;}
 private function table_exists():bool{global$wpdb;$table=$wpdb->prefix.'orion_ai_product_index';return$wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s',$table))===$table;}private function terms(int $id,string $taxonomy):array{$terms=wp_get_post_terms($id,$taxonomy,array('fields'=>'names'));return is_wp_error($terms)?array():array_values(array_map('strval',$terms));}private function tokens(string $query):array{$stop=array('what','which','with','that','this','from','have','need','show','find','looking','please','would','could','product','products','for','the','and','are','you','your','some','best','area','suitable','needed');$tokens=preg_split('/[^a-z0-9-]+/i',strtolower($query))?:array();return array_values(array_unique(array_filter($tokens,static fn($t)=>strlen($t)>2&&!in_array($t,$stop,true))));}private function remove_stale(array $ids):void{global$wpdb;if(!$this->table_exists())return;$table=$wpdb->prefix.'orion_ai_product_index';if(!$ids){$wpdb->query("TRUNCATE TABLE {$table}");return;}$safe=implode(',',array_map('absint',$ids));$wpdb->query("DELETE FROM {$table} WHERE product_id NOT IN ({$safe})");}
}
