<?php
if(!defined('ABSPATH')){exit;}
if(!defined('WP_CLI')||!WP_CLI){return;}
final class Orion_AI_CLI_Command{
 /** Show plugin, schema, provider, data and cron health. */
 public function status(array $args,array $assoc_args):void{global$wpdb;$settings=Orion_AI_Settings::get();$provider=Orion_AI_Settings::provider($settings);$tables=array('documents','document_chunks','conversations','messages','events','handoffs');$rows=array();$rows[]=array('check'=>'Plugin version','value'=>ORION_AI_VERSION,'status'=>'OK');$schema=(string)get_option('orion_ai_schema_version','not set');$rows[]=array('check'=>'Schema version','value'=>$schema,'status'=>$schema===ORION_AI_SCHEMA_VERSION?'OK':'MIGRATION NEEDED');$rows[]=array('check'=>'WordPress','value'=>get_bloginfo('version'),'status'=>'OK');$rows[]=array('check'=>'WooCommerce','value'=>defined('WC_VERSION')?WC_VERSION:'Inactive','status'=>defined('WC_VERSION')?'OK':'ERROR');$rows[]=array('check'=>'AI provider','value'=>$provider,'status'=>'OK');$rows[]=array('check'=>'API key','value'=>Orion_AI_Settings::key_source($provider,$settings),'status'=>Orion_AI_Settings::key_configured($provider,$settings)?'OK':'ERROR');foreach($tables as$suffix){$table=$wpdb->prefix.'orion_ai_'.$suffix;$exists=$wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s',$table))===$table;$rows[]=array('check'=>'Table '.$suffix,'value'=>$table,'status'=>$exists?'OK':'MISSING');}if($wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s',$wpdb->prefix.'orion_ai_conversations'))){$column=$wpdb->get_var("SHOW COLUMNS FROM {$wpdb->prefix}orion_ai_conversations LIKE 'state_json'");$rows[]=array('check'=>'Semantic state column','value'=>'state_json','status'=>$column?'OK':'MISSING');}$rows[]=array('check'=>'Knowledge documents','value'=>(string)$this->count($wpdb->prefix.'orion_ai_documents'),'status'=>'INFO');$rows[]=array('check'=>'Knowledge chunks','value'=>(string)$this->count($wpdb->prefix.'orion_ai_document_chunks'),'status'=>'INFO');$rows[]=array('check'=>'Open handoffs','value'=>(string)$this->count($wpdb->prefix.'orion_ai_handoffs',"status='new'"),'status'=>'INFO');$next=wp_next_scheduled(Orion_Cleanup::HOOK);$rows[]=array('check'=>'Cleanup cron','value'=>$next?gmdate('c',$next):'Not scheduled','status'=>$next?'OK':'MISSING');WP_CLI\Utils\format_items('table',$rows,array('check','value','status'));}
 /** Run database migrations. Defaults to a dry run; pass --apply to write. */
 public function migrate(array $args,array $assoc_args):void{$current=(string)get_option('orion_ai_schema_version','not set');WP_CLI::log('Current schema: '.$current);WP_CLI::log('Target schema: '.ORION_AI_SCHEMA_VERSION);if(empty($assoc_args['apply'])){WP_CLI::warning('Dry run only. Back up the database, then rerun with --apply.');return;}Orion_AI_Assistant::run_migrations();WP_CLI::success('Database migrations completed. Schema: '.get_option('orion_ai_schema_version'));}
 /** Test an AI provider. Use --provider=openrouter or --provider=google. */
 public function test_provider(array $args,array $assoc_args):void{$settings=Orion_AI_Settings::get();$provider=sanitize_key((string)($assoc_args['provider']??Orion_AI_Settings::provider($settings)));if(!in_array($provider,array('openrouter','google'),true))WP_CLI::error('Provider must be openrouter or google.');$settings['provider']=$provider;if(!Orion_AI_Settings::key_configured($provider,$settings))WP_CLI::error(ucfirst($provider).' API key is not configured.');$result=Orion_AI_Provider_Factory::create($settings)->chat(array(array('role'=>'user','content'=>'Reply with exactly: Connection successful')));if(empty($result['ok']))WP_CLI::error((string)($result['error']??'Connection failed.'));WP_CLI::success(ucfirst($provider).' connection successful.');}
 /** Reindex knowledge documents. Defaults to a dry run; pass --apply to write. */
 public function reindex(array $args,array $assoc_args):void{global$wpdb;$count=$this->count($wpdb->prefix.'orion_ai_documents');WP_CLI::log('Documents available for reindex: '.$count);if(empty($assoc_args['apply'])){WP_CLI::warning('Dry run only. Rerun with --apply to rebuild chunks.');return;}$done=(new Orion_Knowledge_Base())->reindex_all();WP_CLI::success($done.' document(s) reindexed.');}
 /** Remove expired conversations. Defaults to a dry run; pass --apply to write. */
 public function cleanup(array $args,array $assoc_args):void{global$wpdb;$settings=Orion_AI_Settings::get();$days=absint($settings['retention_days']??30);if($days<1){WP_CLI::warning('Retention cleanup is disabled.');return;}$cutoff=gmdate('Y-m-d H:i:s',time()-$days*DAY_IN_SECONDS);$count=(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$wpdb->prefix}orion_ai_conversations WHERE last_activity < %s",$cutoff));WP_CLI::log('Retention: '.$days.' day(s)');WP_CLI::log('Expired conversations: '.$count);if(empty($assoc_args['apply'])){WP_CLI::warning('Dry run only. Rerun with --apply to delete expired data.');return;}Orion_Cleanup::run();WP_CLI::success('Cleanup batch completed. Run again if more than 1,000 conversations were expired.');}
 /** Manage manager handoffs: `wp orion-ai handoffs list` or `resolve <id> --apply`. */
 public function handoffs(array $args,array $assoc_args):void{global$wpdb;$action=sanitize_key((string)($args[0]??'list'));if('list'===$action){$status=sanitize_key((string)($assoc_args['status']??'new'));$format=sanitize_key((string)($assoc_args['format']??'table'));$where='';$params=array();if(in_array($status,array('new','resolved'),true)){$where=' WHERE status=%s';$params[]=$status;}$sql="SELECT id,status,question,created_at,updated_at FROM {$wpdb->prefix}orion_ai_handoffs{$where} ORDER BY id DESC LIMIT 200";$items=$params?$wpdb->get_results($wpdb->prepare($sql,...$params),ARRAY_A):$wpdb->get_results($sql,ARRAY_A);WP_CLI\Utils\format_items($format,$items?:array(),array('id','status','question','created_at','updated_at'));return;}if('resolve'===$action){$id=absint($args[1]??0);if(!$id)WP_CLI::error('Provide a handoff ID.');if(empty($assoc_args['apply'])){WP_CLI::warning('Dry run only. Rerun with --apply to mark #'.$id.' resolved.');return;}if(!(new Orion_Manager_Handoff())->resolve($id))WP_CLI::error('Handoff could not be updated.');WP_CLI::success('Handoff #'.$id.' marked resolved.');return;}WP_CLI::error('Unknown action. Use list or resolve <id> --apply.');}
 private function count(string $table,string $where=''):int{global$wpdb;$exists=$wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s',$table))===$table;if(!$exists)return 0;return(int)$wpdb->get_var("SELECT COUNT(*) FROM {$table}".($where?' WHERE '.$where:''));}
}
WP_CLI::add_command('orion-ai','Orion_AI_CLI_Command');
