<?php
if(!defined('ABSPATH')){exit;}
final class Orion_Chat_Orchestrator{
 private Orion_Conversation_Service $conversations;private Orion_Rate_Limiter $rate_limiter;private Orion_Knowledge_Base $knowledge;private Orion_Semantic_Product_Planner $planner;private Orion_Intent_Classifier $classifier;private Orion_Context_Manager $context;private Orion_Manager_Handoff $handoff;
 public function __construct(Orion_Conversation_Service $c,Orion_Rate_Limiter $r,Orion_Knowledge_Base $k,Orion_Semantic_Product_Planner $p,Orion_Intent_Classifier $i,Orion_Context_Manager $x,Orion_Manager_Handoff $h){$this->conversations=$c;$this->rate_limiter=$r;$this->knowledge=$k;$this->planner=$p;$this->classifier=$i;$this->context=$x;$this->handoff=$h;}
 public function respond(string $message,string $session_key=''):array|WP_Error{$message=trim(sanitize_textarea_field($message));if($message===''||mb_strlen($message)>1200)return new WP_Error('invalid_message','Please enter a message of up to 1,200 characters.',array('status'=>400));$settings=Orion_AI_Settings::get();if($settings['enabled']!=='1')return new WP_Error('disabled','The assistant is currently unavailable.',array('status'=>503));$rate=$this->rate_limiter->check($settings);if(is_wp_error($rate))return$rate;$conversation=$this->conversations->resolve($session_key,$settings);if(is_wp_error($conversation))return$conversation;$id=(int)$conversation['id'];$history=$this->conversations->history($id);$state=$this->conversations->state($id);$classification=$this->classifier->classify($message,$history,$state,$settings);$state=$this->context->apply($state,$classification);$this->conversations->save_state($id,$state);$this->conversations->record_event('intent_classified',array('intent'=>$classification['intent'],'topic'=>$classification['topic'],'confidence'=>$classification['confidence']),$id);
  if(!empty($classification['needs_clarification'])&&!empty($classification['clarifying_questions']))return$this->finish($conversation,$settings,$message,'I need a little more information before I can give you a reliable answer.',array(),array(),array(),'clarification_requested',$classification['clarifying_questions']);
  return match($classification['intent']){'store_policy'=>$this->policy($conversation,$settings,$message,$classification,$state),'project_recommendation','product_search'=>$this->products($conversation,$settings,$message,$classification,$state),'manager_follow_up'=>$this->refer($conversation,$settings,$message,$classification,$state,'This question needs confirmation from our team.'),default=>$this->general($conversation,$settings,$message,$history,$state)};
 }
 private function policy(array $conversation,array $settings,string $message,array $classification,array $state):array|WP_Error{$query=$classification['policy_query']?:$message;$docs=$this->knowledge->relevant($query,5);if(!$docs)return$this->refer($conversation,$settings,$message,$classification,$state,'I do not have confirmed information about that in the store knowledge base.');$provider=Orion_AI_Provider_Factory::create($settings);$prompt='Answer only from the supplied store knowledge. Return JSON only: {"supported":true,"answer":"..."}. Set supported false if the documents do not explicitly answer the question. Never infer delivery areas, prices, dates, policies or guarantees.';$result=$provider->chat(array(array('role'=>'system','content'=>$prompt),array('role'=>'user','content'=>wp_json_encode(array('question'=>$message,'documents'=>$docs)))));$data=!empty($result['ok'])?$this->decode((string)($result['message']['content']??'')):null;if(!is_array($data)||empty($data['supported'])||empty($data['answer']))return$this->refer($conversation,$settings,$message,$classification,$state,'The available store information does not explicitly answer that question.');$sources=$this->sources($docs);return$this->finish($conversation,$settings,$message,sanitize_textarea_field((string)$data['answer']),array(),$sources,$result['usage']??array(),'policy_answered');}
 private function products(array $conversation,array $settings,string $message,array $classification,array $state):array|WP_Error{$kit=$this->planner->recommend($classification,$state,$settings);$required_missing=array();foreach($kit['plan']as$group)if(!empty($group['required'])&&in_array($group['role'],$kit['missing_roles'],true))$required_missing[]=$group['role'];if(!$kit['products']||$required_missing){$reason='I could not find enough confirmed suitable products in the live catalogue.';return$this->refer($conversation,$settings,$message,$classification,array_merge($state,array('missing_roles'=>$required_missing?:$kit['missing_roles'])),$reason,$kit['products']);}$provider=Orion_AI_Provider_Factory::create($settings);$prompt='Write a concise shopping-assistant answer using only the verified live products. Explain each product role. Mention optional or missing roles honestly. Never invent suitability, compatibility, quantity, price, stock or links. Do not output HTML.';$result=$provider->chat(array(array('role'=>'system','content'=>$prompt),array('role'=>'user','content'=>wp_json_encode(array('request'=>$message,'state'=>$state,'verified_products'=>$kit['products'],'missing_roles'=>$kit['missing_roles'])))));$answer=!empty($result['ok'])?trim((string)($result['message']['content']??'')):'';if($answer==='')$answer='I found verified products for this request. Please review the product cards and manufacturer instructions.';return$this->finish($conversation,$settings,$message,$answer,$kit['products'],array(),$result['usage']??array(),'project_recommendation_completed');}
 private function general(array $conversation,array $settings,string $message,array $history,array $state):array|WP_Error{$provider=Orion_AI_Provider_Factory::create($settings);$system=$settings['system_prompt'].' Do not invent store-specific facts, product availability, policies or prices. If the user needs store-specific information, say that confirmed store data is required.';$messages=array(array('role'=>'system','content'=>$system));foreach(array_slice($history,-8)as$item)$messages[]=array('role'=>$item['role'],'content'=>$item['content']);$messages[]=array('role'=>'user','content'=>$message);$result=$provider->chat($messages);if(empty($result['ok']))return new WP_Error('ai_error',$result['error'],array('status'=>502));$answer=trim((string)($result['message']['content']??''));if($answer==='')$answer='I could not prepare a reliable answer.';return$this->finish($conversation,$settings,$message,$answer,array(),array(),$result['usage']??array(),'general_answered');}
 private function refer(array $conversation,array $settings,string $message,array $classification,array $state,string $reason,array $products=array()):array|WP_Error{$id=$this->handoff->create((int)$conversation['id'],$message,array('reason'=>$reason,'classification'=>$classification,'state'=>$state));$this->conversations->record_event('manager_follow_up_needed',array('handoff_id'=>$id,'topic'=>$classification['topic']??''),(int)$conversation['id']);$answer=$reason.' I have added this question to the manager follow-up queue';if($id)$answer.=' as reference #'.$id;$answer.='.';return$this->finish($conversation,$settings,$message,$answer,$products,array(),array(),'manager_follow_up_created');}
 private function finish(array $conversation,array $settings,string $question,string $answer,array $products,array $sources,array $usage,string $event,array $questions=array()):array|WP_Error{$id=(int)$conversation['id'];$limit=(int)$settings['questions_per_session'];if(!$this->conversations->increment($id,$limit))return new WP_Error('session_limit','This chat session has ended.',array('status'=>429));$this->conversations->save_exchange($id,$question,$answer,$usage);$this->conversations->record_event($event,array('products'=>count($products)),$id);return array('answer'=>$answer,'message'=>$answer,'questions'=>$questions,'products'=>$this->unique_products($products),'estimate'=>null,'sources'=>$sources,'actions'=>$products?array(array('type'=>'add_to_cart','label'=>'Add available products individually')):array(),'remaining'=>max(0,$limit-((int)$conversation['question_count']+1)),'sessionLimit'=>$limit,'session'=>(string)$conversation['session_key']);}
 private function decode(string $text):?array{$text=trim(preg_replace('/^```(?:json)?\s*|\s*```$/i','',trim($text)));$data=json_decode($text,true);if(is_array($data))return$data;if(preg_match('/\{[\s\S]*\}/',$text,$m)){$data=json_decode($m[0],true);return is_array($data)?$data:null;}return null;}
 private function sources(array $docs):array{$out=array();foreach($docs as$d)if(!empty($d['source_url']))$out[$d['source_url']]=array('title'=>$d['title'],'url'=>$d['source_url']);return array_values($out);}
 private function unique_products(array $products):array{$out=array();foreach($products as$p)if(!empty($p['id']))$out[(int)$p['id']]=$p;return array_values($out);}
}
