<?php
if(!defined('ABSPATH')){exit;}
final class Orion_Conversation_Service{
 private string $conversations_table;private string $messages_table;private string $events_table;
 public function __construct(){global$wpdb;$this->conversations_table=$wpdb->prefix.'orion_ai_conversations';$this->messages_table=$wpdb->prefix.'orion_ai_messages';$this->events_table=$wpdb->prefix.'orion_ai_events';}
 public function resolve(string $session_key,array $settings):array|WP_Error{global$wpdb;$hash=$this->client_hash();$day=wp_date('Y-m-d');$cutoff=gmdate('Y-m-d H:i:s',time()-((int)$settings['session_minutes']*MINUTE_IN_SECONDS));$limit=(int)$settings['questions_per_session'];if($this->valid_session($session_key)){$row=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$this->conversations_table} WHERE session_key=%s AND client_hash=%s AND day_key=%s AND last_activity>=%s LIMIT 1",$session_key,$hash,$day,$cutoff),ARRAY_A);if($row&&(int)$row['question_count']<$limit)return$row;}$row=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$this->conversations_table} WHERE client_hash=%s AND day_key=%s AND last_activity>=%s AND question_count<%d ORDER BY id DESC LIMIT 1",$hash,$day,$cutoff,$limit),ARRAY_A);if($row)return$row;$count=(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$this->conversations_table} WHERE client_hash=%s AND day_key=%s",$hash,$day));if($count>=(int)$settings['sessions_per_day'])return new WP_Error('daily_limit',(string)$settings['limit_message'],array('status'=>429));$now=current_time('mysql',true);$wpdb->insert($this->conversations_table,array('client_hash'=>$hash,'session_key'=>wp_generate_uuid4(),'day_key'=>$day,'question_count'=>0,'last_activity'=>$now,'created_at'=>$now,'state_json'=>'{}'));if(!$wpdb->insert_id)return new WP_Error('session_error','The chat session could not be created.',array('status'=>500));return$wpdb->get_row($wpdb->prepare("SELECT * FROM {$this->conversations_table} WHERE id=%d",$wpdb->insert_id),ARRAY_A);}
 public function history(int $id):array{global$wpdb;$rows=$wpdb->get_results($wpdb->prepare("SELECT role,content FROM {$this->messages_table} WHERE conversation_id=%d ORDER BY id DESC LIMIT 12",$id),ARRAY_A)?:array();return array_reverse($rows);}
 public function state(int $id):array{global$wpdb;$json=(string)$wpdb->get_var($wpdb->prepare("SELECT state_json FROM {$this->conversations_table} WHERE id=%d",$id));$state=json_decode($json,true);return is_array($state)?$state:array();}
 public function save_state(int $id,array $state):void{global$wpdb;$wpdb->update($this->conversations_table,array('state_json'=>wp_json_encode($state)),array('id'=>$id));}
 public function save_exchange(int $id,string $q,string $a,array $usage=array()):void{$this->save_message($id,'user',$q,array());$this->save_message($id,'assistant',$a,$usage);}
 public function increment(int $id,int $limit):bool{global$wpdb;$changed=$wpdb->query($wpdb->prepare("UPDATE {$this->conversations_table} SET question_count=question_count+1,last_activity=%s WHERE id=%d AND question_count<%d",current_time('mysql',true),$id,$limit));return 1===$changed;}
 public function record_event(string $type,array $payload=array(),int $id=0):void{global$wpdb;$wpdb->insert($this->events_table,array('conversation_id'=>$id?:null,'event_type'=>sanitize_key($type),'payload_json'=>wp_json_encode($payload),'created_at'=>current_time('mysql',true)));}
 public function analytics(int $days=30):array{global$wpdb;$days=max(1,min(365,$days));$since=gmdate('Y-m-d H:i:s',time()-$days*DAY_IN_SECONDS);$events=$wpdb->get_results($wpdb->prepare("SELECT event_type,COUNT(*) total FROM {$this->events_table} WHERE created_at>=%s GROUP BY event_type ORDER BY total DESC",$since),ARRAY_A)?:array();$conversations=(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$this->conversations_table} WHERE created_at>=%s",$since));return array('days'=>$days,'conversations'=>$conversations,'events'=>$events);}
 private function save_message(int $id,string $role,string $content,array $usage):void{global$wpdb;$wpdb->insert($this->messages_table,array('conversation_id'=>$id,'role'=>$role,'content'=>$content,'usage_json'=>$usage?wp_json_encode($usage):null,'created_at'=>current_time('mysql',true)));}
 private function client_hash():string{$uid=get_current_user_id();$visitor=isset($_COOKIE['orion_ai_visitor'])?sanitize_text_field(wp_unslash($_COOKIE['orion_ai_visitor'])):'';$identity=$uid?'user:'.$uid:'guest:'.$visitor.'|'.($_SERVER['REMOTE_ADDR']??'').'|'.substr($_SERVER['HTTP_USER_AGENT']??'',0,200);return hash_hmac('sha256',$identity,wp_salt('auth'));}
 private function valid_session(string $v):bool{return(bool)preg_match('/^[a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i',$v);}
}
